### ISSUE TITLE
Error(s) in loading state_dict for Resampler:\n\tsize mismatch for proj_out.weight

### ISSUE THREAD

**Issue by unrulpkk** [ashleykleynhans/runpod-worker-instantid#2]
When I replace the model with Justin-Choo/XXMix_9realisticSDXL( https://huggingface.co/Justin-Choo/XXMix_9realisticSDXL), I get an error. The error is: 
Error(s) in loading state_dict for Resampler:\n\tsize mismatch for proj_out.weight: copying a param with shape torch.Size([2048, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1280]).\n\tsize mismatch for proj_out.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([768]).\n\tsize mismatch for norm_out.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([768]).\n\tsize mismatch for norm_out.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([768]).

 What should I pay attention to when replacing the model?

**Comment by ashleykleynhans** [comment]
I don't know - ask here https://github.com/InstantID/InstantID
