### ISSUE TITLE
Watercolor is always the style

### ISSUE THREAD

**Issue by jarnowu** [ashleykleynhans/runpod-worker-instantid#3]
No matter what I add to the style_name ("style_name": "cyberpunk" for example), watercolor is always sent out as the style. I use your original version of the repo.

**Comment by ashleykleynhans** [comment]
Either change the prompt or log an issue in the InstantID project on GitHub:
https://github.com/InstantID/InstantID

**Comment by ashleykleynhans** [comment]
Sorry I misunderstood, will check it out.

**Comment by ashleykleynhans** [comment]
Its case sensitive, you need to match the EXACT name of the style in the [style_template.py](https://github.com/ashleykleynhans/runpod-worker-instantid/blob/main/src/style_template.py) file.  If you don't match the style correctly, it defaults to Watercolor instead.
