### ISSUE TITLE
Error when loading custom .safetensors file

### ISSUE THREAD

**Issue by Q-D-C** [ashleykleynhans/runpod-worker-instantid#4]
After downloading a model from civit.ai using wget inside of a pod to a network volume. After entering the path in the generate.py file I get the following error:

`RunPod request sync-0ccb3bbb-38b5-4f76-85e5-d94d2c525a46-e1 failed
{
    "delayTime": 101811,
    "error": "StableDiffusionXLPipeline.__init__() got an unexpected keyword argument 'safety_checker'",
    "executionTime": 21511,
    "id": "sync-0ccb3bbb-38b5-4f76-85e5-d94d2c525a46-e1",
    "output": {
        "output": "Traceback (most recent call last):\n  File \"/runpod-volume/runpod-worker-instantid/src/rp_handler.py\", line 313, in handler\n    images = generate_image(\n  File \"/runpod-volume/runpod-worker-instantid/src/rp_handler.py\", line 282, in generate_image\n    PIPELINE = get_instantid_pipeline(model)\n  File \"/runpod-volume/runpod-worker-instantid/src/rp_handler.py\", line 100, in get_instantid_pipeline\n    (tokenizers, text_encoders, unet, _, vae) = load_models_xl(\n  File \"/runpod-volume/runpod-worker-instantid/src/model_util.py\", line 357, in load_models_xl\n    (tokenizers, text_encoders, unet, vae) = load_checkpoint_model_xl(\n  File \"/runpod-volume/runpod-worker-instantid/src/model_util.py\", line 325, in load_checkpoint_model_xl\n    pipe = StableDiffusionXLPipeline.from_single_file(\n  File \"/workspace/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py\", line 118, in _inner_fn\n    return fn(*args, **kwargs)\n  File \"/workspace/venv/lib/python3.10/site-packages/diffusers/loaders/single_file.py\", line 263, in from_single_file\n    pipe = download_from_original_stable_diffusion_ckpt(\n  File \"/workspace/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py\", line 1687, in download_from_original_stable_diffusion_ckpt\n    pipe = pipeline_class(\nTypeError: StableDiffusionXLPipeline.__init__() got an unexpected keyword argument 'safety_checker'\n"
    },
    "status": "FAILED"
}`

The model was added to generate.py like this:

`MODEL_PATH = '/workspace/runpod-worker-instantid/src/yes.safetensors' `

**Comment by ashleykleynhans** [comment]
Probably not an SDXL model, and if it is, log an issue here: https://github.com/InstantID/InstantID  - this just uses their code so can't be fixed here.
